### ISSUE TITLE
Feedback on Milestone #2

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/os_stress_survey#12]
Excellent work team! Your data wrangling and EDA is superb, lots of informative, well constructed figures. You did a good job critically evaluating your survey design. Your document is readable, a couple more subheaders within the figures section detailing what parameters are being analyzed could have made it flow a bit better. But that is fairly minor - great work!

**Comment by jessimk** [comment]
Noted-- Thank you!
